### ISSUE TITLE
Error: Could not locate the bindings file. Tried:

### ISSUE THREAD

**Issue by dreaddymck** [rsrdesarrollo/node-fqdn#2]
Running

`var fqdn = require('node-fqdn');
console.log("FQDN:", fqdn());
`

on a: Linux raspberrypi 4.9.59-v7+ #1047 SMP Sun Oct 29 12:19:23 GMT 2017 armv7l GNU/Linux

results in:

`/home/pi/git/gate/node_modules/node-fqdn/node_modules/deasync/node_modules/bindings/bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /home/pi/git/gate/node_modules/node-fqdn/node_modules/deasync/build/deasync.node
 → /home/pi/git/gate/node_modules/node-fqdn/node_modules/deasync/build/Debug/deasync.node
 → /home/pi/git/gate/node_modules/node-fqdn/node_modules/deasync/build/Release/deasync.node
 → /home/pi/git/gate/node_modules/node-fqdn/node_modules/deasync/out/Debug/deasync.node
 → /home/pi/git/gate/node_modules/node-fqdn/node_modules/deasync/Debug/deasync.node
 → /home/pi/git/gate/node_modules/node-fqdn/node_modules/deasync/out/Release/deasync.node
 → /home/pi/git/gate/node_modules/node-fqdn/node_modules/deasync/Release/deasync.node
 → /home/pi/git/gate/node_modules/node-fqdn/node_modules/deasync/build/default/deasync.node
 → /home/pi/git/gate/node_modules/node-fqdn/node_modules/deasync/compiled/9.3.0/linux/arm/deasync.node
    at bindings (/home/pi/git/gate/node_modules/node-fqdn/node_modules/deasync/node_modules/bindings/bindings.js:88:9)
    at /home/pi/git/gate/node_modules/node-fqdn/node_modules/deasync/index.js:34:32
    at Object.<anonymous> (/home/pi/git/gate/node_modules/node-fqdn/node_modules/deasync/index.js:76:2)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
`
Is there a solution to this?

**Comment by dreaddymck** [comment]
Closing issue. 

Something broke the application permissions. 

Though fqdn has been replaced. Removing and re-installing all the node_nodules solved everything else.
